apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: online-boutique
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.4
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 350Mi  # Increased from 300Mi - Java needs headroom
        # Startup probe: allows up to 120s for JVM warmup before liveness kicks in
        startupProbe:
          grpc:
            port: 9555
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 12  # 10 + (10 * 12) = 130s max startup time
        readinessProbe:
          grpc:
            port: 9555
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 3
        livenessProbe:
          grpc:
            port: 9555
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: online-boutique
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
