apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: online-boutique
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: server
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.4
        ports:
        - containerPort: 7070
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
        readinessProbe:
          grpc:
            port: 7070
          initialDelaySeconds: 15
        livenessProbe:
          grpc:
            port: 7070
          initialDelaySeconds: 15
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: online-boutique
spec:
  selector:
    app: cartservice
  ports:
  - port: 7070
    targetPort: 7070
