apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: online-boutique
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: server
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice:v0.10.4
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          grpc:
            port: 8080
          periodSeconds: 5
        livenessProbe:
          grpc:
            port: 8080
          periodSeconds: 5
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: online-boutique
spec:
  selector:
    app: emailservice
  ports:
  - port: 5000
    targetPort: 8080
