apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: online-boutique
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice:v0.10.4
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        resources:
          requests:
            cpu: 100m
            memory: 96Mi   # Increased from 64Mi
          limits:
            cpu: 200m
            memory: 192Mi  # Increased from 128Mi - Node.js needs more headroom
        # Startup probe: allows up to 45s for Node.js startup before liveness kicks in
        startupProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 8  # 5 + (5 * 8) = 45s max startup time
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: online-boutique
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
