apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-frontend-proxy
  namespace: tailscale
  labels:
    app: tailscale-frontend-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-frontend-proxy
  template:
    metadata:
      labels:
        app: tailscale-frontend-proxy
    spec:
      serviceAccountName: tailscale-proxy
      containers:
        - name: tailscale
          image: tailscale/tailscale:latest
          imagePullPolicy: Always
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
            - name: TS_HOSTNAME
              value: "online-boutique"
            - name: TS_STATE_DIR
              value: "/var/lib/tailscale"
            - name: TS_USERSPACE
              value: "true"
            - name: TS_SERVE_CONFIG
              value: "/config/serve.json"
          volumeMounts:
            - name: state
              mountPath: /var/lib/tailscale
            - name: serve-config
              mountPath: /config
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        - name: state
          emptyDir: {}
        - name: serve-config
          configMap:
            name: tailscale-serve-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-serve-config
  namespace: tailscale
data:
  serve.json: |
    {
      "TCP": {
        "443": {
          "HTTPS": true
        }
      },
      "Web": {
        "${TS_CERT_DOMAIN}:443": {
          "Handlers": {
            "/": {
              "Proxy": "http://frontend.online-boutique.svc.cluster.local:80"
            }
          }
        }
      }
    }
