apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-proxy
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-proxy
subjects:
- kind: ServiceAccount
  name: proxies
  namespace: tailscale
roleRef:
  kind: ClusterRole
  name: tailscale-proxy
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxies
  namespace: tailscale
