apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-proxy
  namespace: tailscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-proxy
  namespace: tailscale
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-proxy
  namespace: tailscale
subjects:
  - kind: ServiceAccount
    name: tailscale-proxy
    namespace: tailscale
roleRef:
  kind: Role
  name: tailscale-proxy
  apiGroup: rbac.authorization.k8s.io
