apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 5.*
    helm:
      valuesObject:
        # Pin to Falco 0.43.0 (latest stable release)
        image:
          tag: "0.43.0"
        
        # Use modern eBPF driver (no kernel headers needed)
        driver:
          kind: modern_ebpf
        
        # Falco configuration
        falco:
          grpc:
            enabled: true
          jsonOutput: true
          jsonIncludeOutputProperty: true
          httpOutput:
            enabled: true
            url: "http://falcosidekick.falco.svc.cluster.local:2801"
          # Disable external plugin loading - container plugin is compiled-in
          # Loading it externally causes: "a plugin with name 'container' is already loaded"
          load_plugins: []
        
        # Resource limits for minikube
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        
        # Disable artifact download - use bundled rules
        # This removes the flaky init container that times out on DNS
        falcoctl:
          artifact:
            install:
              enabled: false
            follow:
              enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
